// <auto-generated />
namespace AlphaProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddProjectIdToPersonReport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProjectIdToPersonReport));
        
        string IMigrationMetadata.Id
        {
            get { return "201605111131267_AddProjectIdToPersonReport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
